define laser ranger
(
  sensor
  (
    range [0 20.0]
    fov 180.0
    samples 1000
  )
  # generic model properties
  color "black"
  size [ 0.06 0.15 0.03 ]
)

define diff_drive_robot position
(
  pose [ 0.0 0.0 0.0 0.0 ]
  localization "gps" # exact localization

  

  size [ 0.25 0.25 0.40 ]
  origin [ 0.0 0.0 0.0 0.0 ]
  gui_nose 1
  color "red"

  # kinematics
  drive "diff"

  # spawn sensors
  laser(pose [ -0.1 0.0 -0.11 0.0 ])
)
